using OP_API_PURCHASECONTRACT_PROCESS_SRV_0002 from './external/OP_API_PURCHASECONTRACT_PROCESS_SRV_0002';

extend OP_API_PURCHASECONTRACT_PROCESS_SRV_0002.A_PurchaseContract with {
    ZZ_FISCA       : String(12);
    ZZ_FISCA_EMAIL : String(241);
};
